title:             Mohism AI Lab
email:             xalexu@gmail.com
description:       Mohism AI Lab's Blog, focusing on AI and computing technology.
author:            Mohism AI Lab
baseurl:           "/"
url:               "https://mohism-ai-lab.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: monism-ai-lab